name: tasty-golden-easy
version: 0.0.4.2
github: "kafji/tasty-golden-easy"
author: "Kafji"
maintainer: "k@kafji.net"
copyright: "2022 Kafji"

description: Easy golden/expect testing using `tasty-golden`.

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.16
  - aeson >= 2.0
  - aeson-pretty >= 0.8
  - bytestring >= 0.11
  - either >= 5.0
  - filepath >= 1.4
  - split >= 0.2
  - tasty-golden >= 2.3
  - template-haskell >= 2.18
  - th-compat >= 0.1
  - th-env >= 0.1

default-extensions:
  - BlockArguments
  - LambdaCase
  - TemplateHaskell

language: GHC2021

library:
  source-dirs: src

tests:
  tasty-golden-easy-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tasty-golden-easy
      - bytestring
      - tasty
