# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-haskell@v1
        with:
          ghc-version: "9.2.2"
          enable-stack: true

      - name: Restore Cabal cache
        uses: actions/cache@v3.0.2
        with:
          path: ~/.cabal
          key: cabal-${{ runner.os }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            cabal-${{ runner.os }}

      - name: Test
        run: stack test --ghc-options '-j +RTS -A32m -RTS'
